service: lambda-react-hello

frameworkVersion: '2'

provider:
    name: aws
    # runtime: nodejs12.x
    runtime: python3.8  
    stage: dev
    region: us-east-1

functions:
    hello:
        handler: handler.hello
        events:
            - http:
                path: react/hello
                method: get
                cors: true
